Updated README for repo consistency project
newrelic/newrelic-airflow-plugin pull request #16
Opened 2020-10-12 14:44 UTC by bradleycamacho

For context:
https://docs.google.com/document/d/1JIog8rJL9MT6_AbIji8VK_RT3mOuIxC2Xb_xQsVksKk/edit#

https://newrelic.atlassian.net/browse/DOC-6121

2020-10-12 14:50 UTC, a-feld requested changes

2020-10-12 14:50 UTC, a-feld commented on README.rst
> +We encourage your contributions to improve [project name]! Keep in mind
```suggestion
We encourage your contributions to improve newrelic-airflow-plugin! Keep in mind
```

2020-10-12 14:53 UTC, a-feld commented on README.rst
> +-  `New Relic Community <LINK%20to%20specific%20community%20page>`__:
Links are missing here

2020-10-12 14:53 UTC, a-feld commented on README.rst
> +Name <LINK%20TO%20https://opensource.newrelic.com/projects/...%20PAGE>`__.
Links are missing here.

2020-10-12 15:09 UTC, a-feld commented on README.rst
> +2.0 <http://apache.org/licenses/LICENSE-2.0.txt>`__ License. >
Looks like an extra `>` snuck in here.
```suggestion
2.0 <http://apache.org/licenses/LICENSE-2.0.txt>`__ License. 
```

2021-04-16 21:05 UTC, TimPansino commented
@bradleycamacho As with the other repo I ping you on, can this PR be cleaned up so we can merge it, or would you rather close it?

2021-06-15 18:22 UTC, umaannamalai commented
@bradleycamacho touching base with you on this PR as well! If you would like to make the requested changes, we can re-review or we can close this PR out.

2021-06-16 19:36 UTC, closed without merging